name: riverpodtemp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  http: ^0.13.0
  intl: ^0.20.2
  get_it: ^7.6.7
  location: ^5.0.3
  geocoding: ^2.1.1
  auto_route: ^7.8.4
  google_place: ^0.4.7
  #  google_places_flutter: ^2.1.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  country_code_picker: ^3.2.0
  cloud_firestore: ^4.17.5
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.2.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  #  flutter_login_facebook: ^2.0.0
  flutter_facebook_auth: ^7.1.0
  geolocator: ^11.0.0
  #  flutter_vibrate: ^1.3.0
  vibration: ^3.1.3
  flutter_displaymode: ^0.6.0
  flutter_bloc: ^9.1.0

  #ui
  flutter_swipe_detector: ^2.0.0
  image: ^4.1.7
  lottie: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  sms_autofill: ^2.4.1
  google_fonts: ^4.0.4
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.9
  flutter_remix: ^0.0.3
  connectivity_plus: ^5.0.2
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.3.10
  flutter_advanced_switch: ^3.0.1
  crypto: ^3.0.3
  #  flutter_share: ^2.0.0
  share_plus: ^8.0.3
  pull_to_refresh: ^2.0.0
  flutter_masked_text2: ^0.9.1
  image_cropper: ^9.0.0
  floating_draggable_widget: ^2.1.5
  google_maps_flutter: ^2.5.3
  flutter_html: ^3.0.0-alpha.6
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  proste_indexed_stack: ^0.2.4
  osm_nominatim: ^3.0.1
  flutter_carousel_slider: ^1.1.0
  jiffy: ^6.2.2
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.1.0
  confetti: ^0.7.0
  card_swiper: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  webview_flutter: ^4.2.4

  #firebase
  firebase_dynamic_links: ^5.5.7
  firebase_messaging: ^14.7.15
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  intl_phone_field: ^3.2.0
  visibility_detector: ^0.4.0+2
  firebase_ui_auth: ^1.14.0

dependency_overrides:
  http:
dev_dependencies:
# critical for testing. Add this section if missing ---
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottie/
    - assets/
    - assets/temp/
    - assets/images/ui3.png
    - assets/images/splash.png

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/customer.png"
