// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrO0PofWsvgvHHf6eq8DS4mRedxwa5YsA',
    appId: '1:801072125681:android:bcd21d4255359c7cf07b50',
    messagingSenderId: '801072125681',
    projectId: 'grubhouse-bea37',
    databaseURL: 'https://grubhouse-bea37-default-rtdb.firebaseio.com',
    storageBucket: 'grubhouse-bea37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAonqkygzEr-wY7e0okt5uJbPjYlm7iBH8',
    appId: '1:801072125681:ios:501498edb4b15c54f07b50',
    messagingSenderId: '801072125681',
    projectId: 'grubhouse-bea37',
    databaseURL: 'https://grubhouse-bea37-default-rtdb.firebaseio.com',
    storageBucket: 'grubhouse-bea37.appspot.com',
    androidClientId:
        '801072125681-2lptiu01lsrcc49p34fvt4p8lod98r73.apps.googleusercontent.com',
    iosClientId:
        '801072125681-v1ob5pvlhkv4mnk9j5njql1vqc7d6nmk.apps.googleusercontent.com',
    iosBundleId: 'com.grubhouse.customerapp2',
  );
}
